### ISSUE TITLE
UART communication

### ISSUE THREAD

**Issue by gmpgreen** [uvic-auvic/Hydrophones#2]
Step 1: Need to set up and test basic UART communication (same as motor controller 2.0 issue)

Step 2: In the future, an output buffer will need to be set up to send four channels of 14bit values simultaneously

**Comment by poornack** [comment]
Since we are going to be sending out large amounts of data, it is worth investigating using DMA for UART. There is a branch in the Motor Controller 2 repo named UART_with_DMA. There is one bug with it, but it works for the most part. Whoever picks this task up should fix that bug and look into porting that code over to this repo. Make sure there are no conflicts between the DMA streams used by the ADC code first. Ask Gabe about this. If there is a conflict, ADC should get the priority and UART will need to be done using interrupts.

**Comment by poornack** [comment]
Merged to master.
